### ISSUE TITLE
JavaScript refresher + Typescript

### ISSUE THREAD

**Issue by hungnp194** [zinza-d2-training/haoth-react#1]
- JavaScript refresher
  - https://github.com/zinza-d2-training/new-to-react/blob/fresher/01_Day_JavaScript_Refresher/01_javascript_refresher.md

- Tìm hiểu về Typescript
  - [Spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) 
  - [Destructing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)
  - [Object reference and cloning](https://javascript.info/object-copy)
  - [Default Types](https://www.typescriptlang.org/docs/handbook/2/everyday-types.html)
  - [Interface/Type](https://www.typescriptlang.org/docs/handbook/2/objects.html)
  - [Generics](https://www.typescriptlang.org/docs/handbook/2/generics.html)
  - [Class](https://www.typescriptlang.org/docs/handbook/2/classes.html)
  - Function type, arrow Func
  - [Advanced Type](https://www.typescriptlang.org/docs/handbook/utility-types.html)

- Bài tập
  - Clone object đã cho, sử dụng spread và destructing. Yêu cầu object và thuộc tính của object đã cloned không có reference tới object cũ [Link](https://codesandbox.io/s/spread-operator-destructing-object-cloning-rjmcy?file=/src/index.js)
  - Viết Model type cho các table database 

![covidtracker](https://user-images.githubusercontent.com/61738572/150733206-6ca87af2-86f0-464e-94b3-ef651c925930.png)

  - Sử dụng các advanced type để viết interface Scalars đại diện cho các kiểu dữ liệu của DB (Ví dụ: Int => number, varchar => string)
  - Sử dụng Scalars để thay thế các type cho model ở trên. Viết các type InsertInput (create api), SetInput (update api) kế thừa từ các model trên. (Ví dụ VaccineInsertInput, VaccineSetInput)

  - Mẫu đã làm [Link](https://www.typescriptlang.org/play#code/C4TwDgpgBAsghiARhAPAFQHxQLxTVAHygDsBXAG3IG4AoGgS2OAgCcAzOAY2gGVO5ycFgGcoAbxpQpUAJJMAXCVIBbZCwA0k6WkYhGwRWVWtN0qABEA9qUTkIhlWtPSAYuUtwDS4xq1SdyhDCwHDKYIrBLIwA5s5S5p4QwPSBEcBRxNF+eBAAHl6RMXFQAGpCnAAWQmkZsdkJzDVF2QH2UIWZNAC+dPqsHNx4KUEhYS70EOQAJqISZpwsEIlTAPqeinwCQsIA2gDkrcGhYHsAusWkYFPLa16bgiL7h6Mn5929TP1c0ADCi8sAVWErHGkxm4myCyWzFWiBAAH5FPAkKh7tt9nJgGcMMUoTc4StSMCWIjYAhkCggawce8GJ92N8oAAhODA0HTUR5ZjEcHPY7smbqKB-aEQKZUlgC2Y9OnMBmDMqcTiMaBciA80QstkTDkQsz0KYbfgPXZ7TFnYrEUJtNGPPZlFiVIQW7JwUjACqWKIALzFRq2dp0xD0TBdZjYLEsyjW0RtxvRZtDbzMwEsMYgpORFNtpvNpxpZmEnuAwn9JoxSeKRcsJZWU3oR2I3Ez5NR8bteYL0jYFHIIBWADcuMqrTCywm85oZaBIKVhyq5MTgHIwO6cFAAAr0TgAaxQipHECFewNe0IUD2VsCZ6IezdHq99F9UxvF4jUfTr72qc-5721ZLL8AOEOsGxCJsIC-HtKH7IclUYZY9gwWgZ2gA8VR4JIVzXXANyEZIBEpYlF1YZdiFXYAMA+OUBl+awmBYEAoDVDVmVZCApT1aQDXHDtK2yK84wDU0HSdFgw2kOCR08ehLGIUs53g0dZOIHZTlpVDhXo9IQBIlgyIo9ct13FAfm0xjj1PP9BKQlDwDo0gGJATCDJwzd8PoQizMcnS9NcyjqK+BV52UuTmPydVwS1DidXBOZuMNKAcwrLFk2kThzP7HikvbXN+LMKSELHHLhJSiSpGgvtBxC5ZeLy1LcUyxRvKcqc6E09DQuIPzsOAIztz3TqZLkyyXz-DKfMYlYrNvQrRzFKDe1gmqYVsmgOpWlSXN6oyPMIobkjknryPdKjZSC352PC7kovYzj4qkbLksTBrsmuRoSvLA5hiOMJyqgCanOmxLnsnSF2IU0H8ukKZoQqSHcrKtKpEBnTmsytr1vs4V2OOwzcIG0z2NGr93sg8bMuBr9+GBYRSbhunkKx2cfnY7aTr63C9vIIngTx07AvlaAJWuyLNTu2LZmyJ7EZe-62HoERgBWQS6v2USqnE5GoEEYIVetNX7XKTX-ogZQ4HochDY151tbAVlhAAdy9EHZZtrXMc0iV+c5zdCYlEm-wVpX9evP9deVmy-zNi3yC-e3hCdl21q94l2fx9z9M8nnvfk0jeqoqQgA)

**Comment by tahuuhao** [comment]
1.  Javascript refresher
  - String:  Tìm hiểu các hàm string
    toUpperCase(): Viết hoa chuỗi,return string
    toLowerCase():  Viết thường chuỗi,return string
    substr(i,j): cắt chuỗi từ vị trí thứ i, lấy ra j phần tử (i,j bắt buộc),return string
    substring(i,j): cắt chuỗi từ vị trí thứ i lấy j phần tử hoặc đến khi găp phần tử null(k dùng tham số j),return string
    split(): chia chuỗi thành 1 mảng gồm các phần tử được ngăn cách bởi kí tự trong split, return array
    trim(): Xóa bỏ khoảng trắng 2 đầu của chuỗi, return string
    includes(a): Tìm kiếm a tồn tại trong chuỗi hay không, return true/false
    replace(old,new):thay thế old bằng new, return string
    concat(sub1, sub2, sub3): Nối các chuỗi sub1,sub2,sub3 lại với nhau, có thể có nhiều tham số hơn
 -Array: Tìm hiểu mảng và các hàm của mảng
        lenght: trả ra kích thước mảng
        indexOf: kiểm tra tồn tại trong mảng, k tồn tại retrun -1, tồn tại trả ra vị trí thấy đầu tiên
	lastIndexOf: kiểm tra tồn tại trong mảng, k tồn tại retrun -1, tồn tại trả ra vị trí thấy cuối cùng
	includes: kiểm tra tồn tại trong mảng return true/false
	isArray: Kiểm tra kiểu dữ liệu mảng: return true/false
	toString: chuyển mảng thành kiểu dữ liệu chuỗi
	join(a):trả ra 1 chuỗi chèn a vào giữa các phần tử của mảng
	Splice()/Splice(i,j)/Splice(i,j,t): xóa phần tử trong mảng
	push: Thêm phần tử vào cuối mảng
	pop(): Xóa 1 phần tử cuối mảng
	unshift(): thêm phần tử vào đầu mảng
  - Conditionals: Đọc lại if, if else, ,if else if else, switch case, toán tử 3 ngôi
  - Loops: Đọc lại vòng lặp for, while, do whie
       foreach: quan tâm đến vị trí ptu trong mảng,
       for of: Không quan tâm đến vị trí trong mảng,
       for in: sử dụng key truy xuất đến phần tử,
       break: ngắt vòng lặp
       continue: bỏ qua yêu cầu phía sau chạy vòng lặp tiếp theo
 - Scope: Window, Global, Local
 - Object: Property and Method
       assign: sao chép đối tượng gốc sang 1 dối tượng mới
       hasOwnProperty: kiểm tra thuộc tính cuẩ đối tượng có tồn tại không
       keys: trả ra một mảng gồm các keys hoặc properties của đối tượng
       values: trả ra 1 mảng các giá tri thuộc tính của đối tượng
 - Functions: khai báo, hàm không trả về, hàm trả về, hàm không tham số, hàm có tham số, hàm có nhiều tham số, không giới hạn tham số, Expression Function, Self Invoking Functions, Arrow Function
 - Higher Order Function: Callback,Returning function, setInterval, setTimeout
 - Functional Programming: Xem lại các hàm forEach, map, filter, reduce, find, findIndex, some, every
 - Destructing : Giải các giá trị từ mảng thành các biến riêng biệt: [a,b,...rest] = array
 - Spread: Sử dụng như 1 tham số của hàm, sao chép đối tượng

2. Tìm hiểu TypeScript  
- Cải thiện năng suất và tránh lỗi
- Cài đặt: npm install -g typescript
- Type Annotations: Sử dụng chú thích kiểu với cú pháp : [type] để chỉ định rõ ràng kiểu cho một biến, hàm, giá trị trả về của hàm
- Type inference
- Kiểu trong TypeScript
	string, number,boolean: giống javascript
        Object: khai báo đối tượng với các thuộc tính phải được xác định [type], thuoc tinh tuy chon: variable?:[type]
	Array: một mảng là một danh sách các giá trị có thứ tự. Một mảng có thể lưu trữ một loại giá trị hỗn hợp.
		let arr: type[]cú pháp
	any: có thể truy cập bất kì thuộc tính nào, gọi như một hàm, gán cho nó một kiểu dữ liệu bất kì,
	Union Types: hình thành từ hai hoặc nhiều kiểu khác, đại diện cho các giá trị có thể là bất kỳ một trong các kiểu đó
			vi du: id: string|number
	Work Union: Cho phép 1 toán tử hoat động nếu nó hợp lệ với mọi thành viên của Union
	Type Aliases: Sử dụng khi có nhiều đối tượng chung kiểu dữ liệu
	Interfaces: Tương tự như Type Aliases nhưng Interfaces có thể được gọi lại và thêm thuộc tính, kế thừa sử dung extends
	Type Assertions: Nhận giá trị DOM
	Literal Types: Sử dụng các kiểu ký tự chuỗi với các kiểu liên hợp và bí danh kiểu để xác định các kiểu
chấp nhận một tập hợp hữu hạn các ký tự chuỗi.
- Interfaces:
	readonly Properties: thuộc tính chỉ đọc k thể sửa
	Extending Types: đơn kế thừa, đa kế thừa
	Intersection Types: Tạo ra các Type sử dụng toán tử &
	Generic Object Types: Hạn chế các viết lại các hàm
	Readonly Array
-Class
	--strictPropertyInitialization: kiểm soát xem các trường lớp có cần được khởi tạo trong phương thức khởi tạo hay không
	readonly,Constructors, overloads,
	Super Calls: super()
	Methods, Getters / Setters
	implements Clauses: implements interface, implement nhiều interface class C implements A, B {...}
	extends Clauses, Overriding Methods
        Member Visibility
 -Advanced Type:
	Partial<Type>: Xây dựng 1 kiểu với các thuộc tính Type là tùy chọn
	Required<Type>: Xây dựng 1 kiểu bao gồm tất cả thuộc tính Type là bắt buộc
	Readonly<Type> : Xây dựng một kiểu với tất cả các thuộc tính Typeđược đặt thành readonly
	Record<Keys, Type>: Xây dựng 1 kiểu đối tượng có các thuộc tính là Keys và giá trị thuộc tính là Type
	Pick<Type, Keys> : Xây dựng 1 kiểu bằng cách chọn tập hợp các thuộc tính Keys(chuỗi kí tự hoặc liên hợp) của Type 
	Omit<Type, Keys>: Xây dựng một kiểu bằng cách chọn tất cả các thuộc tính Type và sau đó loại bỏ Keys(chuỗi ký tự hoặc liên kết chuỗi ký tự).
	Exclude<UnionType, ExcludedMembers>: Tạo một kiểu bằng cách loại trừ khỏi UnionType tất cả các thành viên liên hiệp có thể gán cho ExcludedMembers
	NonNullable<Type>: Tạo một kiểu bằng cách loại trừ null và undefined từ Type.
	Parameters<Type>
	ConstructorParameters<Type>
	ReturnType<Type>: Xây dựng một kiểu bao gồm kiểu trả về của hàm Type
 3. Bài tập
  [Bài 1](https://codesandbox.io/s/spread-operator-destructing-object-cloning-forked-5p71qc)
  [Bài 2](https://www.typescriptlang.org/play?#code/C4TwDgpgBAsghiARhAPAFQHxQLxTQHwDsBXAG1IFgAoAS0OAgCcAzOAY2gGU25S5GAzgG9qUMVACS9AFxQAcsQC2yRgBpR4tHRB1gshcqbqq4qADFSAezh75SlcdMARS8USkI++0Y1iAavxsABb8spzAjHQA5o6aEAAetuGRhFG+eDSKEALAcIpgYRHRsWJONp5QycXUAL7U1LpMrBySACYiJuI0rWE8fIIA2gDkUsBDALrGdVQN9E3s0ADCjBDlrQBCIB2mbCtrAPqIIAD8svBIqNy8-ALDoxMYU-W0cywLGVnb4rurDK37Nl610GQy0WRyeTAExKUGIYFaB0BlT6N2GYOyuXy0Nqz0abxa6zgAmgCQYhFaAjaqnRqmWvwgGy201mDHx0AAqsTGFBSRByZTCcSvmJmDRBMB9oQ8hUrv1bkMAoxgvxsZ0xHwcpLpUC5cNFcrGKrTBBFHAaKQdaiFYEQobJukwESBAB3SyMHrI4Hy-W21XTUCQKCcphSLnAKRgYjAHBQAAKNDYAGsUMG1ENukN8ENReKtVlM0MNRKpfmsyazaQC46BC63a0hhhqAGOVzOBBw4RI9HcLH+MAaLwU1zQ0wO13GzMXqzmksiSTEnyKVBBRBhVAEQxLSCygwjd9XPRGCB9t0t-L7va1VAeMSBGe7vQ92JWr8gnfPbqRo-L-7wLPiSOjBjlGMbxkmKCLHOqjpvWWYbhABZsAeETHhmWY3tkBYvjYb4Nk2f5QJBxJtsB3Zxn2A6kBBc6AaRE4svMLQBGwbB0POZJLiua4ljKKIgj6KqXqYcBRkEbo0AAXgyUD3qC2i6BM6TMIwliKACUS8V6D5jEJ4jAJY6kQKcsAIMgKCylaF6POkAhicA74WSCF4wrZbr2fsrQ0BChAcLJzlKWQpDHgAbuwrFSn8fnfk8VDNlAzHhRAtERiBPYJsmCVsdBaFDDxBYicAYmRFJsHZipalwBpBb6YZBaufZdVFe5nneRwBbMIFIVhXQax4bFBGZYQEAkSlZG9kBlEoINSWEGGo30VOjFLMhR48gu-LLnO3Hah+VoCXaMVxYsK0gMlnapXG6UQSd2WlXlE5HSdI3nWNFGDsdxCHqds2jvNuKvDO8XdRFNCWIQa0cQKc5QGuSGfShJ4eo557RekoUsT1kW7U5qNXh15BdRjEUMlFOmHQNwM2KDhBnV2oFXYNVNg7diEnYjBbo+FvVZvjQX7JzmMMn1cWM-2YPPXTPZvVRovU7TUYLc8QA)
